### ISSUE TITLE
Cannot test cross-platform cookbooks

### ISSUE THREAD

**Issue by juliandunn** [sethvargo/chefspec#405]
This is something @sethvargo and I discussed privately and I thought I should open an issue here. Seth, feel free to give a more cogent explanation & close it if you feel it can't be solved.

Basically, attempting to test cookbooks intended for one platform (e.g. Windows) on another (e.g. Mac OS X) does not seem to work, because there is no way to stub basic Kernel functionality like 'require'.

Concrete example:

``` ruby
require 'spec_helper'

describe 'foo::windows_web_server' do
  let(:chef_run) { ChefSpec::Runner.new(platform: 'windows', version: '2008R2').converge(described_recipe) }
  before(:each) do
    stub_const("RUBY_PLATFORM", "windows") # you'll see what this is about below
  end
  # expectations below here don't actually matter
end
```

When run on a Mac, this spec fails, because the library from the Windows cookbook is loaded as part of the recipe-under-test, and the following happens:

``` ruby
Failures:

  1) foo::windows_web_server includes the _windows_base role
     Failure/Error: let(:chef_run) { ChefSpec::Runner.new(platform: 'windows', version: '2008R2').converge(described_recipe) }
     LoadError:
       cannot load such file -- win32/registry
     # /var/folders/56/vlf96yyx30vdx5qlq6n4pkxw0000gp/T/d20140401-74327-qv3myy/cookbooks/windows/libraries/registry_helper.rb:26:in `<top (required)>'
     # ./spec/unit/windows_web_server_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/windows_web_server_spec.rb:10:in `block (2 levels) in <top (required)>'
```

Is this just a limitation in unit testing?

**Comment by dhoer** [comment]
This is how I got around this:  
```ruby
let(:chef_run) do
    ChefSpec::SoloRunner.new(platform: 'windows', version: '2008R2') do
      allow_any_instance_of(Chef::DSL::RegistryHelper).to receive(:registry_key_exists?).and_call_original
      allow_any_instance_of(Chef::DSL::RegistryHelper).to receive(:registry_key_exists?).and_return(true)
    end.converge(described_recipe)
end
```

**Comment by daxgames** [comment]
@dhoer - I'll have to try that thanks!

**Comment by dhoer** [comment]
@daxgames - no problem, let me know if that doesn't work for you.

**Comment by dougireton** [comment]
Here's how we fixed it for a Windows spec we needed to run on Macs:

```ruby
RSpec.describe 'chefdk_bootstrap::powershell_profile' do
  # turn off verify_partial_doubles
  # Windows::Helpers#locate_sysnative_cmd is included at Chef run time
  # and is not available when we mock it.
  before do
    RSpec.configure do |config|
      config.mock_with :rspec do |mocks|
        @vpd_setting = mocks.verify_partial_doubles?
        mocks.verify_partial_doubles = false
      end
    end

    allow_any_instance_of(Chef::Recipe)
      .to receive(:locate_sysnative_cmd)
      .with('WindowsPowerShell\v1.0')
      .and_return('C:\WINDOWS\sysnative\WindowsPowerShell\v1.0')
  end

  after do
    RSpec.configure do |config|
      config.mock_with :rspec do |mocks|
        mocks.verify_partial_doubles = @vpd_setting
      end
    end
  end


end
```

**Comment by mcascone** [comment]
@dhoer, sorry to revive this thread, but I am running into this now, and that line you suggested doesn't seem to work for me. Is there another format I should try?

FWIW i am trying unit test a Windows cookbook on a CentOS7 VM.

**Comment by dhoer** [comment]
@mcascone It still seems to work?: https://github.com/dhoer/chef-selenium/blob/9a44b5d7bef566c3b26b31b5e7125126dafef680/spec/unit/node_spec.rb#L28

Try to include a .with specifying the command you intend to mock (or at least a regex) so that you only mock the instances you control.

`allow_any_instance_of(Chef::DSL::RegistryHelper).to receive(:registry_key_exists?).with(foo).and_return(true)`

**Comment by mcascone** [comment]
Thanks for the reply. I'm still not sure how to structure the stub. This is the code that gets shown as the source of the issue (`uninitialized constant WIN32OLE`). I have the `chef-client` recipe in a "core" recipe, that gets run on every node, prior to the node's specific configurations, so every recipe fails.
```
Relevant File Content:
----------------------
/tmp/d20160922-4647-2yhhoe/cookbooks/chef-client/libraries/helpers.rb:

 19:  module Opscode
 20:    module ChefClient
 21:      # helper methods for use in chef-client recipe code
 22:      module Helpers
 23:        include Chef::DSL::PlatformIntrospection
 24:
 25:        def wmi_property_from_query(wmi_property, wmi_query)
 26>>         @wmi = ::WIN32OLE.connect('winmgmts://')
 27:          result = @wmi.ExecQuery(wmi_query)
 28:          return nil unless result.each.count > 0
 29:          result.each.next.send(wmi_property)
 30:        end
 31:
 32:        def chef_client_service_running
 33:          !wmi_property_from_query(:name, "select * from Win32_Service where name = 'chef-client'").nil?
 34:        end
 35:
```

**Comment by dhoer** [comment]
I would probably need an example of the code.  I don't know if following will help, but I will put it out there:

---
I had to wrap blocks around windows specific resources and recipes to make them compatible on linux platforms e.g.,
```ruby
if platform?('windows')
  # do windows stuff
else
  # do linux stuff
end
```

I even had to do this on notifications e.g., 

```ruby
notifies ... if platform?('windows')
notifies ... unless platform?('windows')
```

See https://github.com/dhoer/chef-nexus3/blob/master/providers/default.rb#L83-L113

**Comment by mcascone** [comment]
Literally all i've done that breaks the unit tests on Linux is add the single line:
`include_recipe 'chef-client::default'`

Without that line, the tests run perfectly (and really fast!) on Linux.

**Comment by dhoer** [comment]
I'm afraid I can't help you on this one...

**Comment by mcascone** [comment]
So what we ended up doing was to take the chef-client recipe out of our cookbook, and add it to our nodes' run lists as a separate step. This actually feels better as it removes the dependencies and tests our cookbook in a more isolated fashion. 

Thanks, Max
