### ISSUE TITLE
ChefSpec generating warnings about LWRP resources being redeclared

### ISSUE THREAD

**Issue by lamont** [sethvargo/chefspec#642]
Recently (and with ChefDK 0.8.1 which includes ChefSpec 4.4.0) any cookbook I attempt to test which includes cookbooks with LWRPs generates hundreds of warnings. These warnings are so numerous that all the TravisCI builds for things like chef-cookbooks/chef-client are failing at the rspec logs more than the limit of 4 megabytes. 

I'm assuming this is related to the 12.4 changes about this warning being introduced back in June (which said if you redefine a resource and don't want this error you need an override: true parameter in the new resource). Is there anything I can to do mitigate or suppress the warning (or just see it once) during my rspec/ChefSpec run?

The apt cookbook maintainers are already aware of the issue and point out that it only occurs with ChefSpec::ServerRunner but not ChefSpec::SoloRunner.  https://github.com/chef-cookbooks/apt/issues/163

Errors from the rspec of chef-bareos:

    WARN: You declared a new resource #<Class:0x007fc884f84388> for resource openssl_dhparam, but it comes alphabetically after LWRP resource openssl_dhparam from cookbook openssl and has the same filters ({}), so it will not be used. Use override: true if you want to use it for openssl_dhparam.
    [2015-10-07T14:18:14-07:00] WARN: OpensslDhparam already exists!  Deprecation class overwrites LWRP resource openssl_dhparam from cookbook openssl

And from chef-cookbooks/chef-clients rspec:  (you might need to use my PR: https://github.com/chef-cookbooks/chef-client/pull/343)

     WARN: You declared a new resource #<Class:0x007fd50800aca0> for resource windows_zipfile, but it comes alphabetically after LWRP resource windows_zipfile from cookbook windows and has the same filters ({}), so it will not be used. Use override: true if you want to use it for windows_zipfile.

Apologies if this is not a ChefSpec issue, but it seems to only crop up during rspec runs and it's broken all the lovely TravisCI badges just from the volume logged even if the rspec tests succeed.  Please let me know what I can do to help.

Thank you.

**Comment by zachsmorgan** [comment]
It looks like ChefSpec doesn't do any recycling on the ChefZero instance, so the cookbooks are uploaded for every "runner.converge" triggering that warning. I thought it was just noisy, but maybe it deserves another look if it's killing badges?

**Comment by lamont** [comment]
I've just heard that this was introduced in chef 12.4 and fixed in 12.5.1. I'm testing it now and will close the issue if it's fixed and was a chef-client issue rather than a ChefSpec one.

**Comment by scarolan** [comment]
Is this the same issue?  these WARN messages started showing up recently, and persist with version 12.5.1

rspec -f d --color

sean-1337::default
  When all attributes are default, on an unspecified platform
    downloads the web content tarball
[2015-10-16T16:37:33-05:00] WARN: AptPreference already exists!  Deprecation class overwrites LWRP resource apt_preference from cookbook apt
[2015-10-16T16:37:33-05:00] WARN: AptRepository already exists!  Deprecation class overwrites LWRP resource apt_repository from cookbook apt
    converges successfully
[2015-10-16T16:37:35-05:00] WARN: AptPreference already exists!  Deprecation class overwrites LWRP resource apt_preference from cookbook apt
[2015-10-16T16:37:35-05:00] WARN: AptRepository already exists!  Deprecation class overwrites LWRP resource apt_repository from cookbook apt
    creates index.html

Finished in 6 seconds (files took 9.66 seconds to load)
3 examples, 0 failures

**Comment by kzw** [comment]
Is this the same issue for the following warnings?

./tmp/d20151024-18416-1fl4wzs/cookbooks/chef-client/libraries/helpers.rb:25: warning: already initialized constant Opscode::ChefClient::Helpers::CHEF_SERVER_USER
/tmp/d20151024-18416-1fl4wzs/cookbooks/chef-client/libraries/helpers.rb:25: warning: previous definition of CHEF_SERVER_USER was here

The only way I can make them go away is to combine all 'it' blocks into one.  My knife version is 12.5.1 but I was getting same error with 12.4.4

I also use berkshelf.  I do not get errors when I run the examples in this (chefspec) git repo

**Comment by phs** [comment]
I can confirm this is still happening with `chef-client` 12.5.1

```
$ uname -a
Darwin mylappy 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

```
$ chef --version
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

```
$ grep -i chefspec Gemfile.lock
    chefspec (4.4.0)
  chefspec
```

**Comment by Poohblah** [comment]
I also have been running into this issue with Chef 12.5.1. I was able to get these warnings to go away by using `SoloRunner` instead of `ServerRunner` as mentioned here:

https://github.com/chef-cookbooks/apt/issues/163

**Comment by mtricolici** [comment]
I also have been running into this issue with latest ChefSpec release 4.5.0.

**Comment by jzohrab** [comment]
Hey all, a hack workaround for this is to redirect stdout during the chefspec converge, and restore it afterwards.  Code:
```
  let (:chef_run) do
    # Redirecting stdout to suppress 'Deprecation class overwrites LWRP' noise.
    # (ref https://github.com/sethvargo/chefspec/issues/642)
    old_std_out = $stdout.clone
    $stdout.reopen('tmp_std_out.txt', 'w')
    result = chef_runner.converge(described_recipe)
    $stdout.reopen(old_std_out)
    File.read('tmp_std_out.txt').each_line do |lin|
      puts lin unless lin =~ /Deprecation class overwrites LWRP resource/
    end
    File.delete('tmp_std_out.txt')
    result
  end
```

**Comment by sethvargo** [comment]
Hi everyone, this is being tracked upstream in chef/chef#4668. Thanks! :smile:
